---
output: stevetemplates::cv
geometry: margin=1in

title: "CV"
author: Rocco Zizzamia

#jobtitle: ""
address: "Centre for the Study of African Economies · Manor Rd · Oxford OX1 3UQ, UK"
fontawesome: yes
email: rocco.zizzamia@economics.ox.ac.uk
# github: svmiller
# twitter: stevenvmiller
#osf: "Enter 5 digit osf string here"
#phone: "+44 744 969 5005"
web: roccozizzamia.github.io
#updated: TRUE
#rdateformat: "`r format(Sys.time(), '%d %b %Y')`"

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Appointments

Post-doctoral researcher in Economics (Oxford University) \hfill Nov. 2022-present

Fulford Junior Research Fellow (Somerville College, Oxford University) \hfill Oct. 2023-present

# Education

*University of Oxford*, DPhil, International Development \hfill 2023

*University of Oxford*, MPhil, Development Studies (Distinction)  \hfill 2018

*University of Cape Town*, Bachelor of Arts (Honours) in Economic History (First Class)  \hfill 2015

*University of Cape Town*, Bachelor of Social Science in Philosophy (First Class)  \hfill 2014\
Visiting student, University of California, Berkeley

# Research

## Select publications
Jain, R., Budlender, J., **Zizzamia, R.**, & Bassier, I. (2023). [The labor market and poverty impacts of COVID-19 in South Africa](https://doi.org/10.1111/saje.12356). *South African Journal of Economics.* 91(4), 419-445.

Schotte, S., & **Zizzamia, R.** (2022). [The livelihood impacts of COVID-19 in urban South Africa: A view from below](https://link.springer.com/article/10.1007/s11205-022-02978-7). *Social Indicators Research*. 1-30.

**Zizzamia, R.**, Schotte, S., & Leibbrandt, M. (2022). ([nakes and Ladders and Loaded Dice: Poverty Dynamics and Inequality in South Africa](https://onlinelibrary.wiley.com/doi/full/10.1111/saje.12308), 2008 to 2017. *South African Journal of Economics.* 214-242.

Bassier, I., Budlender, J., **Zizzamia, R.**, Leibbrandt, M., & Ranchhod, V. (2021). [Locked down and locked out: Repurposing social assistance as emergency relief to informal workers.](https://doi.org/10.1016/j.worlddev.2020.105271) *World Development*, 139, 105271.

Clementi, F., Fabiani, M., Molini, V., & **Zizzamia, R.** (2021). [Are We Really Painting the Devil on the Walls? Polarization and its Drivers in Sub-Saharan Africa in the Past Two Decades.](https://doi.org/10.1093/jae/ejab006) *Journal of African Economies.*

**Zizzamia, R.** (2020). [Is employment a panacea for poverty: A mixed-methods investigation into employment decisions in South Africa.](https://doi.org/10.1016/j.worlddev.2020.104938) *World Development.* 130. 104938.

<!-- Leibbrandt, M., Schotte, S., & **Zizzamia, R.** (2019). Tackling persistent poverty and inequality: A dynamic perspective. In *Confronting Inequality: The South African Crisis*, edited by M.S. Smith. Jacana Media. -->

Schotte, S., **Zizzamia, R.**, & Leibbrandt, M. (2018). [A poverty dynamics approach to social stratification: The South African case.](https://doi.org/10.1016/j.worlddev.2018.05.024) *World Development*, 110, 88-103.

## Work in progress

[Improved early action interventions through precise targeting, timely cash, and early warning to mitigate the impacts of climate disasters: Field experimental evidence from Bangladesh](https://www.povertyactionlab.org/initiative-project/improved-early-action-through-precise-targeting-timely-cash-and-early-warning) (with Stefan Dercon, Ashley Pople, Hannah Timmis, Prabhmeet Matta, BIGD Dhaka) 

Improving Graduation Scalability through Group Coaching: Evidence from Bangladesh, the Philippines and Uganda (with Stefan Dercon, Ashley Pople, Emily Beam, and others)

The effect of timely cash transfers during an extreme flood shock: Evidence from the 2022 Pakistan Floods (with Muhammad Bin Khalid, Martin Mattsson, Prabhmeet Matta, and Ashley Pople) 

The effect of anticipatory action in the context of flood shocks in Somalia (with Stefan Dercon and Michael Green) 

Rejection sensitivity and on-the-job search: A lab-in-the-field experiment in South Africa

<!-- Evaluation of BRAC support to village committees during crises within the ultra-poor programme (with Stefan Dercon, Ashley Pople, and BIGD Dhaka) -->

# Research and Teaching Experience

## Research 
Consultant (International Labour Organization) \hfill 2022

Research Assistant (Oxford Department of Social Policy and Intervention) \hfill 2022

Research Officer (Southern African Labour and Develompemnt Research Unit)  \hfill 2016 - 2021

Consultant (National Income Dynamics Study-Coronavirus Rapid Mobile Survey) \hfill 2020

Visiting Fellow (GIGA German Institute for Global and Area Studies) \hfill 2018

Short-Term Consultant (World Bank Group, Poverty Global Practice Unit) \hfill 2017 - 2018

## Teaching 

Teaching Assistant (Oxford Department of International Development) \hfill 2020-2022

Teaching Assistant (Philosophy Department, University of Cape Town) \hfill 2013 - 2014

Teaching Assistant (Religious Studies Department, University of Cape Town) \hfill 2014

# Grants (PI or co-PI)

*Anticipatory action for climate disaster response*, Weiss Asset Management Foundation\
**$1,000,000**  \hfill  2024 - 2025

*Anticipatory action for climate disaster response*, J-Pal King Climate Action Initiative\
**$250,000**  \hfill  2023 - 2025

*Boosting decent employment for Africa’s youth*, International Development Research Centre\
**CAD$500,000**  \hfill  2019 - 2022

*Working to learn: an evaluation of an on-the-job training program*, J-Pal Post-Primary Education Initiative\
**$250,000**  \hfill  2019 - 2022

<!-- *COVID-19 and livelihoods in urban South Africa*, UNU-WIDER\ -->
<!-- **$8,000**  \hfill  2020 - 2021 -->

<!-- *Poverty dynamics in South Africa: A mixed methods investigation*, German Institute for Global and Area Studies\ -->
<!-- **$8,000**  \hfill  2017 -->


# Awards

Clarendon Scholarship \hfill  2019 - 2022

ODID Scholarship \hfill  2022 - 2023

Papiya Ghosh Thesis Prize \hfill 2018

Skye Foundation Scholarship \hfill  2016 - 2018

Michael Wills Scholarship \hfill  2016 - 2018


# Presentations 

**2024** — a2i x GiveDirectly Conference, Dhaka; NOVAFRICA Conference on Economic Development, Lisbon; Oxford Economics Department Jamboree, Oxford

**2023** — Department of Social Policy and Intervention workshop, Oxford; CREB Applied Development Economics, Lahore; ESA Africa Regional Conference, Cape Town; Path2Dev Conference, LUMS, Lahore

**2022** — WB/IZA/UNU-WIDER Conference, Cape Town; CSAE Workshop, Oxford

**2021** — UNU-WIDER Seminar, Helsinki; RESEP Seminar, Stellenbosch; Oxford Department of International Development, Oxford; CSAE Workshop, Oxford

**2020** — Oxford Department of International Development, Oxford; Agence Française de Développement, Paris; SALDRU, Cape Town; African Centre for Excellence in Inequality Research, Cape Town; IUSSP Population, Poverty and Inequality Research Conference, remote

**2019** — IDRC/ILO/INCLUDE Workshop, Nairobi; WB/IZA/UNU-WIDER Conference, Bangkok; IUSSP Conference, University of Michigan

**2018** — CSAE Conference, Oxford; SALDRU Seminar, Cape Town; RESEP Seminar, Stellenbosch; African Studies Centre, Oxford; INET-YSI Africa Convening, Harare; HDCA Conference, Buenos Aires; AFD Conference, Paris; GIGA Seminar, Hamburg

**2017** — Fifth Congress of African Economists, Malabo; HDCA Conference, Cape Town; CSAE Conference, Oxford; African Studies Centre, Oxford

**2016** — DSA Conference, Oxford; SALDRU Seminar, Cape Town; International Workshop on the Middle Class in Africa, Cape Town


# Public engagement
My research has been featured in the Financial Times, The Economist, The Guardian, among others. 

<!-- # Professional service  -->
<!-- ## Organization -->

<!-- ## Refereeing -->

<!-- ## Mentoring -->

# Other information
**Software** - Python, Stata, R

**Languages** - English, Italian

**Sport** - Oxford University First Marathon Team and half-Blue (2022/23). Marathon PB: 2h28

# References
Available upon request

